use ard/async
use ard/duration
use ard/http
use ard/io
use ard/sqlite

use maestro/db
use maestro/predictions
use maestro/matches
use maestro/teams

fn sync() {
  let conn = db::connect()

  async::start(fn() {
    while {
      predictions::find_good_odds()
      async::sleep(duration::from_hours(2))
    }
  })

  while {
    matches::sync(conn)
    async::sleep(duration::from_hours(2))
  }

  conn.close().expect("Failed to close database")
}
